_wandb:
    value:
        cli_version: 0.22.1
        e:
            7bblt2vdawpzltyaqdzmjrmmzoo90jpr:
                codePath: examples/demo.ipynb
                cpu_count: 6
                cpu_count_logical: 6
                disk:
                    /:
                        total: "1081101176832"
                        used: "7218900992"
                email: curtisgribben1@gmail.com
                executable: /usr/local/bin/python
                git:
                    commit: ea19c6be56499ee203a024c7ec9f2aab60ee83ae
                    remote: https://github.com/cgribben1/Streaming_Service_Recommendation_Simulation.git
                host: 935d9355af8e
                memory:
                    total: "3773542400"
                os: Linux-6.6.87.2-microsoft-standard-WSL2-x86_64-with-glibc2.41
                program: /app/Streaming_Service_Recommendation_Simulation/examples/demo.ipynb
                python: CPython 3.10.18
                root: /app/Streaming_Service_Recommendation_Simulation/film_recommender
                startedAt: "2025-11-09T12:52:39.847219Z"
                writerId: 7bblt2vdawpzltyaqdzmjrmmzoo90jpr
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 5
                - 53
            "2":
                - 5
                - 53
            "3":
                - 2
                - 15
            "4": 3.10.18
            "5": 0.22.1
            "8":
                - 1
            "12": 0.22.1
            "13": linux-x86_64
